package minify

import (
	"bytes"
	"errors"
	"io"
	"sort"
	"unicode/utf8"
	"unsafe"

	"github.com/tdewolff/parse/v2/buffer"
)

// ErrOutOfRange is returned when a generated position is outside the minified output.
var ErrOutOfRange = errors.New("generated position out of range")

// Location is a position in the original (unminified) source.
// Line and LinePos are 1-based. LinePos is a byte column within the line
// (matching go/token.Position), not a rune or UTF-16 column.
type Location struct {
	Offset  int // byte offset into original source
	Line    int // 1-based
	LinePos int // 1-based, byte-based column within the line
}

// Index maps generated (minified) byte offsets back to original source positions.
// It retains only the segment list, line-start arrays, and output length — not
// the original or minified text. After MinifyMapped/BytesMapped returns, Index is
// immutable and its public API is safe for concurrent use.
//
// Segments are exact (slope-1 pass-through equal to pristine) or non-exact (whole
// run maps to one original offset). Attribute-embedded JS/CSS often maps only to
// the attribute start; TemplateDelims tokens usually stay exact.
type Index struct {
	segs      []segment
	origLines []int // byte offsets of line starts in original
	genLines  []int // byte offsets of line starts in generated
	outLen    int
	srcLen    int // original source length (for end-of-source mapping)
}

// segment is a maximal run of generated bytes sharing one mapping rule.
type segment struct {
	gen    int  // start offset in generated output
	orig   int  // original offset (start of slope-1 run, or point target)
	length int  // length in generated space
	exact  bool // true → slope-1; false → all bytes map to orig
}

// coverage returns the fraction of generated bytes that are exactly mapped.
// Test-only surface; re-exported as Coverage from mapping_test.go.
func (ix *Index) coverage() float64 {
	if ix == nil || ix.outLen == 0 {
		return 0
	}
	exact := 0
	for i := range ix.segs {
		if ix.segs[i].exact {
			exact += ix.segs[i].length
		}
	}
	return float64(exact) / float64(ix.outLen)
}

// Original maps a generated byte offset to an original Location.
// gen may be equal to the output length (one-past-the-end, e.g. unexpected EOF).
// exact is true only for slope-1 pass-through segments with gen < outLen
// (there is a generated byte to compare). At gen == outLen, exact is always false.
func (ix *Index) Original(gen int) (loc Location, exact bool, err error) {
	if ix == nil || gen < 0 || gen > ix.outLen {
		return Location{}, false, ErrOutOfRange
	}
	if ix.outLen == 0 {
		return locationAt(ix.origLines, 0), false, nil
	}
	if gen == ix.outLen {
		return ix.endLocation()
	}
	seg := ix.segmentAt(gen)
	if seg.exact {
		off := seg.orig + (gen - seg.gen)
		return locationAt(ix.origLines, off), true, nil
	}
	return locationAt(ix.origLines, seg.orig), false, nil
}

// OriginalForPosition maps a 1-based line and byte column in the *minified*
// output to an original Location. The caller need not re-supply the minified text.
func (ix *Index) OriginalForPosition(line, col int) (loc Location, exact bool, err error) {
	if ix == nil {
		return Location{}, false, ErrOutOfRange
	}
	gen, err := positionToOffset(ix.genLines, ix.outLen, line, col)
	if err != nil {
		return Location{}, false, err
	}
	return ix.Original(gen)
}

func (ix *Index) endLocation() (Location, bool, error) {
	if len(ix.segs) == 0 {
		return locationAt(ix.origLines, ix.srcLen), false, nil
	}
	last := ix.segs[len(ix.segs)-1]
	off := last.orig
	if last.exact {
		off = last.orig + last.length
		if off > ix.srcLen {
			off = ix.srcLen
		}
	}
	// One-past-the-end: no generated byte to compare, so exact is always false.
	return locationAt(ix.origLines, off), false, nil
}

func (ix *Index) segmentAt(gen int) segment {
	// segs cover [0, outLen) contiguously when non-empty.
	if len(ix.segs) == 0 {
		return segment{}
	}
	i := sort.Search(len(ix.segs), func(i int) bool {
		return ix.segs[i].gen+ix.segs[i].length > gen
	})
	if i >= len(ix.segs) {
		return ix.segs[len(ix.segs)-1]
	}
	return ix.segs[i]
}

////////////////////////////////////////////////////////////////

// origInterval is a half-open range [start, end) of pristine offsets claimed exact.
type origInterval struct {
	start, end int
}

// findOrigOverlap reports whether [o,end) intersects any claimed interval.
func findOrigOverlap(claimed []origInterval, o, end int) (bool, origInterval) {
	// claimed is sorted by start. Find first with start < end and end > o.
	i := sort.Search(len(claimed), func(i int) bool {
		return claimed[i].end > o
	})
	if i < len(claimed) && claimed[i].start < end {
		return true, claimed[i]
	}
	return false, origInterval{}
}

// addOrigInterval inserts [o,end) into the sorted merged claim list.
func addOrigInterval(claimed []origInterval, o, end int) []origInterval {
	if end <= o {
		return claimed
	}
	i := sort.Search(len(claimed), func(i int) bool {
		return claimed[i].start > o
	})
	// Merge with previous if overlapping or abutting.
	if i > 0 && claimed[i-1].end >= o {
		i--
		if end > claimed[i].end {
			claimed[i].end = end
		}
		if o < claimed[i].start {
			claimed[i].start = o
		}
	} else {
		claimed = append(claimed, origInterval{})
		copy(claimed[i+1:], claimed[i:])
		claimed[i] = origInterval{start: o, end: end}
	}
	// Merge forward while overlapping/abutting.
	for i+1 < len(claimed) && claimed[i].end >= claimed[i+1].start {
		if claimed[i+1].end > claimed[i].end {
			claimed[i].end = claimed[i+1].end
		}
		claimed = append(claimed[:i+1], claimed[i+2:]...)
	}
	return claimed
}

////////////////////////////////////////////////////////////////

// MinifyMapped minifies input and builds a mapping Index from generated offsets
// back to the original source. The caller's input slice is not mutated.
//
// It copies input into a working buffer so minifiers may rewrite tokens in place
// while a pristine view is kept for line-starts and exactness checks.
func (m *M) MinifyMapped(mediatype string, w io.Writer, input []byte) (*Index, error) {
	return m.minifyMapped(mediatype, w, input)
}

// BytesMapped minifies v and returns the minified bytes plus a mapping Index.
// The caller's v is not mutated. On error it returns the original v, a nil Index,
// and the error (same slice-on-error pattern as Bytes). Use MinifyMapped when you
// need the Index of a partial write on failure.
func (m *M) BytesMapped(mediatype string, v []byte) ([]byte, *Index, error) {
	out := buffer.NewWriter(make([]byte, 0, len(v)))
	ix, err := m.minifyMapped(mediatype, out, v)
	if err != nil {
		return v, nil, err
	}
	return out.Bytes(), ix, nil
}

func (m *M) minifyMapped(mediatype string, w io.Writer, input []byte) (*Index, error) {
	// Working copy: spare byte for parse.NewInputBytes NULL terminator without realloc.
	working := make([]byte, len(input), len(input)+1)
	copy(working, input)

	tw := newTrackingWriter(w, working, input)
	err := m.Minify(mediatype, tw, buffer.NewReader(working))
	ix := tw.finish(len(input))
	return ix, err
}

////////////////////////////////////////////////////////////////

// Not safe for concurrent use.
type trackingWriter struct {
	w        io.Writer
	working  []byte // minifier mutates this; used for subslice offset recovery
	pristine []byte // immutable original; used for exactness and line-starts
	segs     []segment
	genPos   int
	genLines []int
	lastOrig int
	hasLast  bool
	// lastWasCR is true when the previous Write ended with a lone '\r' that
	// was recorded as a newline. If the next Write starts with '\n', that
	// completes a CRLF and must not open a second line.
	lastWasCR bool
	// claimed tracks pristine [start,end) ranges already used by an exact segment.
	// A second write of the same working subslice (e.g. JS Var.Data at every use)
	// must not be marked exact again — occurrence identity would be wrong even
	// though byte-equality still holds.
	claimed []origInterval
}

func newTrackingWriter(w io.Writer, working, pristine []byte) *trackingWriter {
	return &trackingWriter{
		w:        w,
		working:  working,
		pristine: pristine,
		genLines: []int{0},
	}
}

func (t *trackingWriter) Write(b []byte) (int, error) {
	n, err := t.w.Write(b)
	if n > 0 {
		t.record(b[:n])
		t.noteGenLines(b[:n])
		t.genPos += n
	}
	return n, err
}

func (t *trackingWriter) finish(srcLen int) *Index {
	return &Index{
		segs:      t.segs,
		origLines: lineStarts(t.pristine),
		genLines:  t.genLines,
		outLen:    t.genPos,
		srcLen:    srcLen,
	}
}

func (t *trackingWriter) record(b []byte) {
	gen := t.genPos
	if off, ok := offsetIn(t.working, b); ok {
		if off+len(b) <= len(t.pristine) && bytes.Equal(b, t.pristine[off:off+len(b)]) {
			if t.claimExact(gen, off, len(b)) {
				return
			}
			// Multi-emit of an already-claimed original range (shared AST slice).
			// Map non-exact to the recovered slice offset (typically the binding).
			t.recordNonExact(gen, off, len(b))
			return
		}
		// Subslice of working but bytes differ from pristine: rewritten in place
		// (whitespace collapse, entity decode, number minify, …). Align b against
		// pristine at off, skipping pristine whitespace that was deleted.
		t.recordAligned(gen, b, off)
		return
	}
	// Synthesized (scratch buffer, AST keyword literals, inserted punctuation, …).
	// Exact-cursor prefix match only: content must equal pristine contiguously
	// after the last exact segment. No whole-buffer search — that mis-attributed
	// common substrings (e.g. minified CSS → random HTML text nodes).
	if n := t.exactPrefixLen(b); n > 0 {
		expect, _ := t.exactCursor()
		// Point-map the unmatched tail at the first pristine byte not covered
		// (not the token start, and not the last matched byte).
		restOrig := expect + n
		if restOrig >= len(t.pristine) {
			restOrig = len(t.pristine) - 1
		}
		if restOrig < 0 {
			restOrig = 0
		}
		t.recordExactThenRest(gen, b, n, restOrig)
		return
	}
	orig := 0
	if t.hasLast {
		orig = t.lastOrig
	}
	t.recordNonExact(gen, orig, len(b))
}

// recordAligned maps a rewritten working subslice by aligning through deleted
// whitespace so collapsed multi-line text keeps source line identity (no free
// substring search).
func (t *trackingWriter) recordAligned(gen int, b []byte, off int) {
	if len(b) == 0 {
		return
	}
	if off < 0 {
		off = 0
	}
	pi := off
	bi := 0
	for bi < len(b) {
		// Longest equal run at (bi, pi).
		n := 0
		for bi+n < len(b) && pi+n < len(t.pristine) && b[bi+n] == t.pristine[pi+n] {
			if hit, _ := findOrigOverlap(t.claimed, pi+n, pi+n+1); hit {
				break
			}
			n++
		}
		if n > 0 {
			if !t.claimExact(gen+bi, pi, n) {
				// Range was claimed between the check and claim; fall through.
				t.recordNonExact(gen+bi, pi, len(b)-bi)
				return
			}
			bi += n
			pi += n
			continue
		}
		// Skip pristine whitespace deleted by collapse (e.g. tab after newline).
		if pi < len(t.pristine) && isMapWhitespace(t.pristine[pi]) {
			// Do not skip if the next output byte is this same whitespace —
			// that byte still needs to map (single kept space/newline).
			if bi < len(b) && b[bi] == t.pristine[pi] {
				// Equal but claimed (overlap break above) — non-exact remainder.
				t.recordNonExact(gen+bi, pi, len(b)-bi)
				return
			}
			pi++
			continue
		}
		// True rewrite (entity, number, etc.): non-exact for the rest.
		restOrig := pi
		if restOrig >= len(t.pristine) {
			restOrig = len(t.pristine) - 1
		}
		if restOrig < 0 {
			restOrig = 0
		}
		t.recordNonExact(gen+bi, restOrig, len(b)-bi)
		return
	}
}

func isMapWhitespace(c byte) bool {
	// Align with parse.IsWhitespace: space, \t, \n, \r, \f.
	return c == ' ' || c == '\t' || c == '\n' || c == '\r' || c == '\f'
}

// claimExact records an exact slope-1 segment for pristine[orig:orig+length]
// if that range has not already been claimed. Returns false on multi-emit.
func (t *trackingWriter) claimExact(gen, orig, length int) bool {
	if length <= 0 || orig < 0 || orig+length > len(t.pristine) {
		return false
	}
	end := orig + length
	if hit, _ := findOrigOverlap(t.claimed, orig, end); hit {
		return false
	}
	t.appendSeg(gen, orig, length, true)
	t.claimed = addOrigInterval(t.claimed, orig, end)
	t.lastOrig = end - 1
	t.hasLast = true
	return true
}

func (t *trackingWriter) recordNonExact(gen, orig, length int) {
	if length <= 0 {
		return
	}
	t.appendSeg(gen, orig, length, false)
	t.lastOrig = orig
	t.hasLast = true
}

// exactCursor returns the pristine offset immediately after the last exact
// segment. When there are no segments yet, the cursor is 0 (start of source).
// When the last segment is non-exact there is no reliable contiguous cursor.
func (t *trackingWriter) exactCursor() (expect int, ok bool) {
	if n := len(t.segs); n > 0 {
		last := t.segs[n-1]
		if !last.exact {
			return 0, false
		}
		return last.orig + last.length, true
	}
	return 0, true
}

// exactPrefixLen is the longest N such that b[:N] equals pristine at the exact
// cursor and those pristine bytes are not already claimed exact.
func (t *trackingWriter) exactPrefixLen(b []byte) int {
	expect, ok := t.exactCursor()
	if !ok || expect < 0 || expect > len(t.pristine) {
		return 0
	}
	max := len(b)
	if rem := len(t.pristine) - expect; rem < max {
		max = rem
	}
	n := 0
	for n < max && b[n] == t.pristine[expect+n] {
		if hit, _ := findOrigOverlap(t.claimed, expect+n, expect+n+1); hit {
			break
		}
		n++
	}
	return n
}

// recordExactThenRest records b[:n] as exact at the current exact cursor, then
// the remainder as non-exact point-mapped to restOrig.
func (t *trackingWriter) recordExactThenRest(gen int, b []byte, n, restOrig int) {
	expect, _ := t.exactCursor()
	if !t.claimExact(gen, expect, n) {
		t.recordNonExact(gen, restOrig, len(b))
		return
	}
	if n < len(b) {
		t.appendSeg(gen+n, restOrig, len(b)-n, false)
		t.lastOrig = restOrig
		t.hasLast = true
	}
}

func (t *trackingWriter) appendSeg(gen, orig, length int, exact bool) {
	if length == 0 {
		return
	}
	if n := len(t.segs); n > 0 {
		last := &t.segs[n-1]
		if last.exact == exact && last.gen+last.length == gen {
			if exact && last.orig+last.length == orig {
				last.length += length
				return
			}
			if !exact && last.orig == orig {
				last.length += length
				return
			}
		}
	}
	t.segs = append(t.segs, segment{gen: gen, orig: orig, length: length, exact: exact})
}

func (t *trackingWriter) noteGenLines(b []byte) {
	// Must match lineStarts. lastWasCR stitches CRLF across Writes; multi-byte
	// separators (U+2028/U+2029) are not re-stitched across Writes.
	base := t.genPos
	i := 0
	if t.lastWasCR {
		t.lastWasCR = false
		if len(b) > 0 && b[0] == '\n' {
			// Complete CRLF started in a previous write: the line start was
			// recorded after '\r'; move it past the '\n'.
			if n := len(t.genLines); n > 0 {
				t.genLines[n-1] = base + 1
			}
			i = 1
		}
	}
	for i < len(b) {
		c := b[i]
		n := 1
		newline := false
		if c == '\n' {
			newline = true
		} else if c == '\r' {
			newline = true
			if i+1 < len(b) && b[i+1] == '\n' {
				n = 2
			}
		} else if c >= 0xC0 {
			r, size := utf8.DecodeRune(b[i:])
			if size > 1 && (r == '\u2028' || r == '\u2029') {
				newline = true
				n = size
			} else if size > 1 {
				n = size
			}
		}
		i += n
		if newline {
			t.genLines = append(t.genLines, base+i)
		}
	}
	if len(b) > 0 {
		// Lone trailing '\r' may complete as CRLF on the next Write.
		// A completed "\r\n" ends with '\n', so lastWasCR stays false.
		t.lastWasCR = b[len(b)-1] == '\r'
	}
}

// offsetIn reports whether b is a subslice of buf and returns the byte offset.
// Empty b is never a subslice. Address arithmetic is within one allocation only
// and never converted back to a pointer; exact claims still require pristine equality.
func offsetIn(buf, b []byte) (int, bool) {
	if len(b) == 0 || len(buf) == 0 {
		return 0, false
	}
	bp := uintptr(unsafe.Pointer(&b[0]))
	bufp := uintptr(unsafe.Pointer(&buf[0]))
	if bp < bufp {
		return 0, false
	}
	off := int(bp - bufp)
	if off > len(buf) || off+len(b) > len(buf) {
		return 0, false
	}
	return off, true
}

////////////////////////////////////////////////////////////////

// lineStarts returns byte offsets of each line start, matching parse.Position
// newline rules: \n, \r, \r\n, U+2028, U+2029.
func lineStarts(src []byte) []int {
	starts := make([]int, 1, 8)
	starts[0] = 0
	for i := 0; i < len(src); {
		c := src[i]
		n := 1
		newline := false
		if c == '\n' {
			newline = true
		} else if c == '\r' {
			newline = true
			if i+1 < len(src) && src[i+1] == '\n' {
				n = 2
			}
		} else if c >= 0xC0 {
			r, size := utf8.DecodeRune(src[i:])
			if size > 1 && (r == '\u2028' || r == '\u2029') {
				newline = true
				n = size
			} else if size > 1 {
				n = size
			}
		}
		i += n
		if newline {
			starts = append(starts, i)
		}
	}
	return starts
}

func locationAt(lineStarts []int, offset int) Location {
	if offset < 0 {
		offset = 0
	}
	// Empty table (zero-value Index, or missing lineStarts): treat as one line at 0.
	if len(lineStarts) == 0 {
		return Location{Offset: offset, Line: 1, LinePos: offset + 1}
	}
	// Largest lineStarts[i] <= offset.
	i := sort.Search(len(lineStarts), func(j int) bool {
		return lineStarts[j] > offset
	}) - 1
	if i < 0 {
		i = 0
	}
	start := lineStarts[i]
	return Location{
		Offset:  offset,
		Line:    i + 1,
		LinePos: offset - start + 1,
	}
}

func positionToOffset(lineStarts []int, totalLen, line, col int) (int, error) {
	if line < 1 || col < 1 || len(lineStarts) == 0 {
		return 0, ErrOutOfRange
	}
	if line > len(lineStarts) {
		return 0, ErrOutOfRange
	}
	start := lineStarts[line-1]
	off := start + col - 1
	// Allow one-past end of this line (or file): start <= off <= lineEnd.
	var lineEnd int
	if line < len(lineStarts) {
		lineEnd = lineStarts[line]
	} else {
		lineEnd = totalLen
	}
	if off < start || off > lineEnd || off > totalLen {
		return 0, ErrOutOfRange
	}
	return off, nil
}
