package minify

import (
	"bytes"
	"fmt"
	"io"
	"strings"
	"testing"

	"github.com/tdewolff/parse/v2"
	"github.com/tdewolff/test"
)

// Coverage re-exports coverage for tests (including package minify_test).
// Not part of the stable library API.
func (ix *Index) Coverage() float64 { return ix.coverage() }

// reportAudit logs the audit report and fails on gen structural issues.
// Exact overlaps are reported loudly; failExact makes them a test failure
// (correctness: exact multi-emit is wrong even when byte-equality holds).
func reportAudit(t *testing.T, name string, a SegmentAudit, failExact bool) {
	t.Helper()
	if a.Report != "" {
		t.Log("\n" + a.Report)
	}
	if a.GenIssues > 0 {
		t.Errorf("%s: %d generated-space structural issue(s)", name, a.GenIssues)
	}
	if a.ExactOverlaps > 0 {
		msg := fmt.Sprintf("%s: %d exact orig overlap(s) covering %d generated bytes (multi-emit)",
			name, a.ExactOverlaps, a.ExactOverlapB)
		if failExact {
			t.Error(msg)
		} else {
			t.Log(msg)
		}
	}
	if a.ExactOutOfOrder > 0 {
		t.Logf("%s: %d out-of-order exact first-claims (no overlap; informational)", name, a.ExactOutOfOrder)
	}
}

func TestOffsetIn(t *testing.T) {
	buf := []byte("hello world")
	off, ok := offsetIn(buf, buf[6:11])
	test.That(t, ok)
	test.T(t, off, 6)

	_, ok = offsetIn(buf, []byte("world"))
	test.That(t, !ok)

	_, ok = offsetIn(buf, nil)
	test.That(t, !ok)

	_, ok = offsetIn(buf, buf[0:0])
	test.That(t, !ok)
}

func TestLineStartsAndLocation(t *testing.T) {
	src := []byte("ab\nc\r\nde\r")
	starts := lineStarts(src)
	test.T(t, starts, []int{0, 3, 6, 9})

	loc := locationAt(starts, 0)
	test.T(t, loc, Location{Offset: 0, Line: 1, LinePos: 1})
	loc = locationAt(starts, 4)
	test.T(t, loc, Location{Offset: 4, Line: 2, LinePos: 2})
	loc = locationAt(starts, 6)
	test.T(t, loc, Location{Offset: 6, Line: 3, LinePos: 1})
}

func TestNoteGenLinesCRLFSplitAcrossWrites(t *testing.T) {
	// "\r\n" must be one newline even when the two bytes arrive in separate Writes.
	pristine := []byte("a\r\nb")
	working := make([]byte, len(pristine), len(pristine)+1)
	copy(working, pristine)

	var out bytes.Buffer
	tw := newTrackingWriter(&out, working, pristine)
	_, err := tw.Write([]byte("a\r"))
	test.Error(t, err)
	_, err = tw.Write([]byte("\nb"))
	test.Error(t, err)

	ix := tw.finish(len(pristine))
	want := lineStarts(out.Bytes())
	test.T(t, ix.genLines, want)
	test.T(t, want, []int{0, 3})

	// Bare CR then non-LF must not adjust the previous line start.
	out.Reset()
	tw = newTrackingWriter(&out, working, []byte("a\rb"))
	_, err = tw.Write([]byte("a\r"))
	test.Error(t, err)
	_, err = tw.Write([]byte("b"))
	test.Error(t, err)
	ix = tw.finish(3)
	test.T(t, ix.genLines, lineStarts(out.Bytes()))
	test.T(t, ix.genLines, []int{0, 2})
}

func TestOriginalEOFExactFalse(t *testing.T) {
	m := New()
	m.AddFunc("dummy/copy", func(_ *M, w io.Writer, r io.Reader, _ map[string]string) error {
		return writeReaderBytes(w, r)
	})
	src := []byte("hello")
	out, ix, err := m.BytesMapped("dummy/copy", src)
	test.Error(t, err)
	loc, exact, err := ix.Original(len(out))
	test.Error(t, err)
	test.That(t, !exact)
	test.T(t, loc.Offset, len(src))
}

func TestZeroValueIndexOriginal(t *testing.T) {
	// Zero-value Index must not panic (empty origLines).
	var ix Index
	loc, exact, err := ix.Original(0)
	test.Error(t, err)
	test.That(t, !exact)
	test.T(t, loc, Location{Offset: 0, Line: 1, LinePos: 1})

	// Nil receiver still errors.
	var nix *Index
	_, _, err = nix.Original(0)
	test.T(t, err, ErrOutOfRange)
}

func TestBytesMappedErrorNilIndex(t *testing.T) {
	m := New()
	m.AddFunc("dummy/fail", func(_ *M, w io.Writer, _ io.Reader, _ map[string]string) error {
		_, _ = w.Write([]byte("partial"))
		return fmt.Errorf("minify failed")
	})
	in := []byte("input")
	out, ix, err := m.BytesMapped("dummy/fail", in)
	test.That(t, err != nil)
	test.That(t, ix == nil)
	test.Bytes(t, out, in)
}

func TestTrackingWriterClassification(t *testing.T) {
	pristine := []byte("hello   world")
	working := make([]byte, len(pristine), len(pristine)+1)
	copy(working, pristine)

	var out bytes.Buffer
	tw := newTrackingWriter(&out, working, pristine)

	// Verbatim pass-through of "hello".
	_, err := tw.Write(working[0:5])
	test.Error(t, err)

	// In-place whitespace collapse (like parse.ReplaceMultipleWhitespace).
	// The returned subslice often sits over the surviving characters and can
	// still verify exact against pristine at its recovered offset.
	collapsed := parse.ReplaceMultipleWhitespace(working[5:])
	_, err = tw.Write(collapsed)
	test.Error(t, err)

	// Synthesized literal.
	_, err = tw.Write([]byte(";"))
	test.Error(t, err)

	ix := tw.finish(len(pristine))
	test.That(t, len(ix.segs) >= 2)

	// First "hello" is exact slope-1.
	loc, exact, err := ix.Original(0)
	test.Error(t, err)
	test.That(t, exact)
	test.T(t, loc.Offset, 0)

	loc, exact, err = ix.Original(4)
	test.Error(t, err)
	test.That(t, exact)
	test.T(t, loc.Offset, 4)

	// After collapse, generated " world" maps exactly onto pristine[7:13].
	loc, exact, err = ix.Original(5)
	test.Error(t, err)
	test.That(t, exact)
	test.T(t, loc.Offset, 7)

	// Synthesized ";" inherits last original byte of previous write.
	semiGen := ix.outLen - 1
	loc, exact, err = ix.Original(semiGen)
	test.Error(t, err)
	test.That(t, !exact)
	test.T(t, loc.Offset, 12)
}

func TestTrackingWriterSynthesizedExactExtension(t *testing.T) {
	// After an exact run, a synthesized buffer that continues the pristine
	// stream byte-for-byte must extend the exact segment (coverage win).
	pristine := []byte("hello world!")
	working := make([]byte, len(pristine), len(pristine)+1)
	copy(working, pristine)

	var out bytes.Buffer
	tw := newTrackingWriter(&out, working, pristine)

	// Exact pass-through of "hello ".
	_, err := tw.Write(working[0:6])
	test.Error(t, err)

	// Synthesized copy of "world" (new allocation, not a subslice of working).
	syn := append([]byte(nil), pristine[6:11]...)
	_, err = tw.Write(syn)
	test.Error(t, err)

	// Synthesized "!" then junk that does not match pristine.
	_, err = tw.Write([]byte("!?"))
	test.Error(t, err)

	ix := tw.finish(len(pristine))
	// "hello world!" should be exact; trailing "?" non-exact.
	for g := 0; g < len("hello world!"); g++ {
		loc, exact, err := ix.Original(g)
		test.Error(t, err)
		test.That(t, exact)
		test.T(t, loc.Offset, g)
		test.T(t, out.Bytes()[g], pristine[g])
	}
	loc, exact, err := ix.Original(len("hello world!"))
	test.Error(t, err)
	test.That(t, !exact)
	_ = loc
	// 12 of 13 generated bytes exact.
	test.That(t, ix.Coverage() > 0.9)
}

func TestTrackingWriterWhitespaceCollapseMultiline(t *testing.T) {
	// HTML text token spanning two source lines: "\n\t" collapsed to "\n".
	// Second line must map to its own source line, not the token start.
	pristine := []byte("<p>hello,\n\tworld</p>")
	working := make([]byte, len(pristine), len(pristine)+1)
	copy(working, pristine)
	var out bytes.Buffer
	tw := newTrackingWriter(&out, working, pristine)

	// <p>
	_, err := tw.Write(working[0:3])
	test.Error(t, err)
	// Text with collapse of "\n\t" → "\n" (same as parse.ReplaceMultipleWhitespace).
	text := working[3 : len(working)-4] // "hello,\n\tworld"
	collapsed := parse.ReplaceMultipleWhitespace(text)
	test.Bytes(t, collapsed, []byte("hello,\nworld"))
	_, err = tw.Write(collapsed)
	test.Error(t, err)
	// </p>
	_, err = tw.Write(working[len(working)-4:])
	test.Error(t, err)

	ix := tw.finish(len(pristine))
	minified := out.Bytes()
	// "world" in output
	wi := bytes.Index(minified, []byte("world"))
	test.That(t, wi >= 0)
	loc, exact, err := ix.Original(wi)
	test.Error(t, err)
	test.That(t, exact)
	// Original "world" starts after "\n\t"
	want := bytes.Index(pristine, []byte("world"))
	test.T(t, loc.Offset, want)
	test.T(t, loc.Line, 2)
}

func TestTrackingWriterNoForwardSearchFalseExact(t *testing.T) {
	// Synthesized "function" after a dropped comment must NOT leap to a later
	// occurrence (that heuristic mis-mapped CSS onto HTML text). Non-exact to
	// start-of-source / inherit is honest until an explicit name channel exists.
	pristine := []byte("// drop me\nfunction x(){}")
	working := make([]byte, len(pristine), len(pristine)+1)
	copy(working, pristine)
	var out bytes.Buffer
	tw := newTrackingWriter(&out, working, pristine)

	_, err := tw.Write([]byte("function"))
	test.Error(t, err)
	ix := tw.finish(len(pristine))
	loc, exact, err := ix.Original(0)
	test.Error(t, err)
	test.That(t, !exact)
	test.T(t, loc.Offset, 0)
}

func TestTrackingWriterMultiEmitClaimOnce(t *testing.T) {
	// Shared-slice multi-emit: first "name" is exact at binding; later writes of
	// the same slice are non-exact to that binding (no forward search for uses).
	pristine := []byte("var name=name+name")
	working := make([]byte, len(pristine), len(pristine)+1)
	copy(working, pristine)
	var out bytes.Buffer
	tw := newTrackingWriter(&out, working, pristine)

	name := working[4:8] // "name" at binding
	_, err := tw.Write([]byte("var "))
	test.Error(t, err)
	_, err = tw.Write(name)
	test.Error(t, err)
	_, err = tw.Write([]byte("="))
	test.Error(t, err)
	_, err = tw.Write(name)
	test.Error(t, err)
	_, err = tw.Write([]byte("+"))
	test.Error(t, err)
	_, err = tw.Write(name)
	test.Error(t, err)

	ix := tw.finish(len(pristine))
	a := ix.AuditSegments(pristine, out.Bytes())
	test.T(t, a.ExactOverlaps, 0)

	loc, exact, err := ix.Original(4)
	test.Error(t, err)
	test.That(t, exact)
	test.T(t, loc.Offset, 4)
	for _, genAt := range []int{9, 14} {
		loc, exact, err = ix.Original(genAt)
		test.Error(t, err)
		test.That(t, !exact)
		test.T(t, loc.Offset, 4) // binding
	}
}

func TestTrackingWriterSynthesizedNoFalseExact(t *testing.T) {
	// Inserted punctuation that does not equal the next pristine byte must
	// stay non-exact (e.g. ASI semicolon where original had none).
	pristine := []byte("ab")
	working := make([]byte, len(pristine), len(pristine)+1)
	copy(working, pristine)

	var out bytes.Buffer
	tw := newTrackingWriter(&out, working, pristine)
	_, err := tw.Write(working[0:1]) // "a"
	test.Error(t, err)
	_, err = tw.Write([]byte(";")) // synthesized; pristine next is "b"
	test.Error(t, err)
	_, err = tw.Write(working[1:2]) // "b"
	test.Error(t, err)

	ix := tw.finish(len(pristine))
	_, exact, err := ix.Original(1)
	test.Error(t, err)
	test.That(t, !exact)

	// "b" is still exact via subslice, not via extension past the semicolon.
	loc, exact, err := ix.Original(2)
	test.Error(t, err)
	test.That(t, exact)
	test.T(t, loc.Offset, 1)
}

func TestTrackingWriterFirstWriteSynthesizedExact(t *testing.T) {
	// First write with no prior segment: cursor is 0.
	pristine := []byte("abc")
	var out bytes.Buffer
	tw := newTrackingWriter(&out, make([]byte, 3, 4), pristine)
	// working is zeroed, so offsetIn won't match equal content from a new slice.
	syn := []byte("abc")
	_, err := tw.Write(syn)
	test.Error(t, err)
	ix := tw.finish(len(pristine))
	test.T(t, ix.Coverage(), 1.0)
	loc, exact, err := ix.Original(2)
	test.Error(t, err)
	test.That(t, exact)
	test.T(t, loc.Offset, 2)
}

func TestAuditGenContiguousOK(t *testing.T) {
	pristine := []byte("abcdef")
	working := make([]byte, len(pristine), len(pristine)+1)
	copy(working, pristine)
	var out bytes.Buffer
	tw := newTrackingWriter(&out, working, pristine)
	_, _ = tw.Write(working[0:3])
	_, _ = tw.Write(working[3:6])
	ix := tw.finish(len(pristine))
	a := ix.AuditSegments(pristine, out.Bytes())
	reportAudit(t, "contiguous", a, true)
	test.T(t, a.GenIssues, 0)
	test.T(t, a.ExactOverlaps, 0)
}

func TestAuditExactOverlapMultiEmitRefused(t *testing.T) {
	// Simulate JS Var.Data: same working subslice written twice.
	// First emit is exact; second must be refused (non-exact) so occurrence
	// identity stays honest and audit reports zero exact overlaps.
	pristine := []byte("xxnameyy")
	working := make([]byte, len(pristine), len(pristine)+1)
	copy(working, pristine)
	var out bytes.Buffer
	tw := newTrackingWriter(&out, working, pristine)
	_, _ = tw.Write(working[0:2]) // "xx" exact
	_, _ = tw.Write(working[2:6]) // "name" exact @2
	_, _ = tw.Write(working[6:8]) // "yy" exact
	_, _ = tw.Write(working[2:6]) // "name" again — must not be exact
	ix := tw.finish(len(pristine))
	a := ix.AuditSegments(pristine, out.Bytes())
	t.Log("\n" + a.Report)
	test.T(t, a.GenIssues, 0)
	test.T(t, a.ExactOverlaps, 0)

	// First "name" at gen 2..6 exact; second "name" at gen 8..12 non-exact @ orig 2.
	loc, exact, err := ix.Original(2)
	test.Error(t, err)
	test.That(t, exact)
	test.T(t, loc.Offset, 2)
	loc, exact, err = ix.Original(8)
	test.Error(t, err)
	test.That(t, !exact)
	test.T(t, loc.Offset, 2)
}

func TestAuditOutOfOrderNoOverlap(t *testing.T) {
	// Emit later original range first, then earlier range — out-of-order but no multi-emit.
	pristine := []byte("ABCDEFGH")
	working := make([]byte, len(pristine), len(pristine)+1)
	copy(working, pristine)
	var out bytes.Buffer
	tw := newTrackingWriter(&out, working, pristine)
	_, _ = tw.Write(working[4:8]) // "EFGH" first
	_, _ = tw.Write(working[0:4]) // "ABCD" second — earlier orig, no overlap
	ix := tw.finish(len(pristine))
	a := ix.AuditSegments(pristine, out.Bytes())
	t.Log("\n" + a.Report)
	test.T(t, a.GenIssues, 0)
	test.T(t, a.ExactOverlaps, 0)
	if a.ExactOutOfOrder < 1 {
		t.Fatalf("expected out-of-order signal, got %d", a.ExactOutOfOrder)
	}
}

func TestAuditSynthesizedNoFalseOverlap(t *testing.T) {
	// Synthesized punctuation between exact runs must not create a false overlap.
	pristine := []byte("ab")
	working := make([]byte, len(pristine), len(pristine)+1)
	copy(working, pristine)
	var out bytes.Buffer
	tw := newTrackingWriter(&out, working, pristine)
	_, _ = tw.Write(working[0:1])
	_, _ = tw.Write([]byte(";")) // does not match pristine[1]=='b'
	_, _ = tw.Write(working[1:2])
	ix := tw.finish(len(pristine))
	a := ix.AuditSegments(pristine, out.Bytes())
	reportAudit(t, "synth-semi", a, true)
	test.T(t, a.ExactOverlaps, 0)
}

func TestTrackingWriterRewrittenInPlace(t *testing.T) {
	// In-place mutation whose bytes no longer match pristine → non-exact
	// point map to the recovered subslice offset (start of the write).
	pristine := []byte("ABC")
	working := make([]byte, len(pristine), len(pristine)+1)
	copy(working, pristine)

	var out bytes.Buffer
	tw := newTrackingWriter(&out, working, pristine)
	parse.ToLower(working)
	_, err := tw.Write(working)
	test.Error(t, err)

	ix := tw.finish(len(pristine))
	loc, exact, err := ix.Original(1)
	test.Error(t, err)
	test.That(t, !exact)
	test.T(t, loc.Offset, 0)
	test.T(t, ix.Coverage(), 0.0)
}

// writeReaderBytes writes r's underlying slice when available so the tracking
// writer can see true input subslices (io.Copy always synthesizes).
func writeReaderBytes(w io.Writer, r io.Reader) error {
	if b, ok := r.(interface{ Bytes() []byte }); ok {
		_, err := w.Write(b.Bytes())
		return err
	}
	_, err := io.Copy(w, r)
	return err
}

func TestBytesMappedDoesNotMutateInput(t *testing.T) {
	m := New()
	m.AddFunc("dummy/copy", func(_ *M, w io.Writer, r io.Reader, _ map[string]string) error {
		return writeReaderBytes(w, r)
	})
	in := make([]byte, 0, 64)
	in = append(in, []byte("hello world")...)
	orig := append([]byte(nil), in...)

	out, ix, err := m.BytesMapped("dummy/copy", in)
	test.Error(t, err)
	test.That(t, ix != nil)
	test.Bytes(t, out, []byte("hello world"))
	test.Bytes(t, in, orig)
	test.That(t, ix.Coverage() == 1.0)
}

func TestFullySynthesizedCoverage(t *testing.T) {
	m := New()
	m.AddFunc("dummy/const", func(_ *M, w io.Writer, _ io.Reader, _ map[string]string) error {
		_, err := w.Write([]byte("CONST"))
		return err
	})
	out, ix, err := m.BytesMapped("dummy/const", []byte("anything"))
	test.Error(t, err)
	test.Bytes(t, out, []byte("CONST"))
	test.T(t, ix.Coverage(), 0.0)
	loc, exact, err := ix.Original(0)
	test.Error(t, err)
	test.That(t, !exact)
	test.T(t, loc.Offset, 0)
}

func TestEmptyInput(t *testing.T) {
	m := New()
	m.AddFunc("dummy/nil", func(_ *M, _ io.Writer, _ io.Reader, _ map[string]string) error {
		return nil
	})
	out, ix, err := m.BytesMapped("dummy/nil", nil)
	test.Error(t, err)
	test.That(t, len(out) == 0)
	test.That(t, ix != nil)
	_, _, err = ix.Original(0)
	test.Error(t, err)
	test.T(t, ix.Coverage(), 0.0)
}

func TestOriginalForPositionDummy(t *testing.T) {
	m := New()
	m.AddFunc("dummy/copy", func(_ *M, w io.Writer, r io.Reader, _ map[string]string) error {
		return writeReaderBytes(w, r)
	})
	src := []byte("ab\ncd")
	_, ix, err := m.BytesMapped("dummy/copy", src)
	test.Error(t, err)

	loc, exact, err := ix.OriginalForPosition(2, 1)
	test.Error(t, err)
	test.That(t, exact)
	test.T(t, loc.Offset, 3)
	test.T(t, loc.Line, 2)
	test.T(t, loc.LinePos, 1)

	_, _, err = ix.OriginalForPosition(0, 1)
	test.T(t, err, ErrOutOfRange)
}

func TestMinifyMappedMatchesBytes(t *testing.T) {
	m := New()
	m.AddFunc("dummy/copy", func(_ *M, w io.Writer, r io.Reader, _ map[string]string) error {
		return writeReaderBytes(w, r)
	})
	src := []byte("hello")
	var buf bytes.Buffer
	ix, err := m.MinifyMapped("dummy/copy", &buf, src)
	test.Error(t, err)
	test.That(t, ix != nil)

	out2, err := m.Bytes("dummy/copy", append([]byte(nil), src...))
	test.Error(t, err)
	test.Bytes(t, buf.Bytes(), out2)
}

// --- segment audit (test-only) ---

// SegmentAudit is a diagnostic report from auditing an Index.
// Test-only (this file); not part of the public library API.
//
// GenIssues are structural failures (generated coverage wrong → lookup broken).
// ExactOverlaps are exact segments whose original range intersects a previously
// claimed exact original range — multi-emit of the same working subslice (e.g.
// JS Var.Data written at every use, all mapping “exact” to the binding). That is
// a correctness bug: byte-equality still holds, so coverage stays high while
// occurrence identity is wrong.
//
// Out-of-order first claims (orig jumps backward into an unclaimed gap) are
// recorded in ExactOutOfOrder for investigation but are not counted as overlaps.
type SegmentAudit struct {
	GenIssues       int
	ExactOverlaps   int
	ExactOverlapB   int // generated bytes in overlapping exact segments
	ExactOutOfOrder int // first-time exact claims with orig < prior high-water (no overlap)
	ExactSegments   int
	ExactBytes      int
	NonExactBytes   int
	SegCount        int
	Report          string
}

// AuditSegments scans the segment list for:
//  1. Generated-space structure: contiguous coverage of [0, outLen), no gaps/overlaps.
//  2. Exact original claims: overlapping ranges (multi-emit) vs mere out-of-order.
//
// pristine and minified are optional but enable context snippets in Report.
// Defined in a test file so package minify and package minify_test can use it
// during `go test` without exporting audit machinery from the library API.
func (ix *Index) AuditSegments(pristine, minified []byte) SegmentAudit {
	var a SegmentAudit
	if ix == nil {
		a.GenIssues = 1
		a.Report = "nil Index\n"
		return a
	}
	a.SegCount = len(ix.segs)

	var b strings.Builder
	fmt.Fprintf(&b, "audit: outLen=%d srcLen=%d segs=%d coverage=%.4f\n",
		ix.outLen, ix.srcLen, len(ix.segs), ix.coverage())

	// --- generated contiguity ---
	expectGen := 0
	for i, s := range ix.segs {
		if s.length <= 0 {
			a.GenIssues++
			fmt.Fprintf(&b, "GEN  seg[%d] non-positive length=%d gen=%d orig=%d exact=%v\n",
				i, s.length, s.gen, s.orig, s.exact)
		}
		if s.gen != expectGen {
			a.GenIssues++
			fmt.Fprintf(&b, "GEN  seg[%d] gen=%d want %d (gap/overlap) length=%d orig=%d exact=%v\n",
				i, s.gen, expectGen, s.length, s.orig, s.exact)
			writeSegContext(&b, "     ", s, pristine, minified)
		}
		if s.exact {
			a.ExactSegments++
			a.ExactBytes += s.length
			if s.orig < 0 || (s.length > 0 && s.orig+s.length > ix.srcLen) || (s.length == 0 && s.orig > ix.srcLen) {
				a.GenIssues++
				fmt.Fprintf(&b, "GEN  seg[%d] exact orig range [%d,%d) outside srcLen=%d\n",
					i, s.orig, s.orig+s.length, ix.srcLen)
				writeSegContext(&b, "     ", s, pristine, minified)
			}
		} else {
			a.NonExactBytes += s.length
			if s.orig < 0 || (ix.srcLen > 0 && s.orig > ix.srcLen) || (ix.srcLen == 0 && s.orig != 0) {
				a.GenIssues++
				fmt.Fprintf(&b, "GEN  seg[%d] non-exact orig=%d outside srcLen=%d\n", i, s.orig, ix.srcLen)
			}
		}
		expectGen = s.gen + s.length
	}
	if expectGen != ix.outLen {
		a.GenIssues++
		fmt.Fprintf(&b, "GEN  segments cover gen [0,%d) but outLen=%d\n", expectGen, ix.outLen)
	}
	if len(ix.segs) == 0 && ix.outLen != 0 {
		a.GenIssues++
		fmt.Fprintf(&b, "GEN  empty segment list but outLen=%d\n", ix.outLen)
	}

	// --- exact original ranges: overlap (multi-emit) vs out-of-order ---
	// Track claimed [start,end) intervals merged and sorted. Overlap ⇒ multi-emit.
	// orig < highWater without overlap ⇒ out-of-order first claim (logged, not fatal).
	var claimed []origInterval
	highWater := 0
	const maxOverlapPrint = 20
	overlapPrinted := 0
	for i := range ix.segs {
		s := &ix.segs[i]
		if !s.exact || s.length <= 0 {
			continue
		}
		o, end := s.orig, s.orig+s.length
		if hit, prev := findOrigOverlap(claimed, o, end); hit {
			a.ExactOverlaps++
			a.ExactOverlapB += s.length
			if overlapPrinted < maxOverlapPrint {
				overlapPrinted++
				fmt.Fprintf(&b, "EXACT-OVERLAP seg[%d] gen=[%d,%d) orig=[%d,%d) intersects claimed [%d,%d)\n",
					i, s.gen, s.gen+s.length, o, end, prev.start, prev.end)
				writeSegContext(&b, "     this  ", *s, pristine, minified)
				if pristine != nil {
					// intersection
					is, ie := o, end
					if prev.start > is {
						is = prev.start
					}
					if prev.end < ie {
						ie = prev.end
					}
					if ie > is {
						fmt.Fprintf(&b, "     pristine intersect [%d,%d): %q\n",
							is, ie, snippet(pristine, is, ie-is))
					}
				}
			}
		} else if o < highWater {
			a.ExactOutOfOrder++
			// Not an overlap: first claim of this range, but emission order went
			// backward into a gap. Useful signal; not treated as multi-emit.
		}
		claimed = addOrigInterval(claimed, o, end)
		if end > highWater {
			highWater = end
		}
	}
	if a.ExactOverlaps > maxOverlapPrint {
		fmt.Fprintf(&b, "EXACT-OVERLAP ... %d more overlap(s) not printed\n", a.ExactOverlaps-maxOverlapPrint)
	}

	if a.GenIssues == 0 && a.ExactOverlaps == 0 {
		fmt.Fprintf(&b, "OK  gen contiguous; no exact orig overlaps (outOfOrder=%d highWater=%d claimedIntervals=%d)\n",
			a.ExactOutOfOrder, highWater, len(claimed))
	} else {
		fmt.Fprintf(&b, "SUMMARY genIssues=%d exactOverlaps=%d exactOverlapBytes=%d exactOutOfOrder=%d exactBytes=%d nonExactBytes=%d\n",
			a.GenIssues, a.ExactOverlaps, a.ExactOverlapB, a.ExactOutOfOrder, a.ExactBytes, a.NonExactBytes)
	}
	a.Report = b.String()
	return a
}

func writeSegContext(b *strings.Builder, prefix string, s segment, pristine, minified []byte) {
	const win = 32
	if minified != nil && s.gen >= 0 && s.gen < len(minified) {
		n := s.length
		if n > win {
			n = win
		}
		fmt.Fprintf(b, "%sminified[%d:]=%q\n", prefix, s.gen, snippet(minified, s.gen, n))
	}
	if pristine != nil && s.orig >= 0 && s.orig < len(pristine) {
		n := s.length
		if !s.exact {
			n = win
		} else if n > win {
			n = win
		}
		fmt.Fprintf(b, "%spristine[%d:]=%q\n", prefix, s.orig, snippet(pristine, s.orig, n))
	}
}

func snippet(b []byte, off, n int) string {
	if b == nil || off < 0 || off >= len(b) || n <= 0 {
		return ""
	}
	end := off + n
	if end > len(b) {
		end = len(b)
	}
	s := make([]byte, 0, end-off)
	for _, c := range b[off:end] {
		switch c {
		case '\n':
			s = append(s, '\\', 'n')
		case '\r':
			s = append(s, '\\', 'r')
		case '\t':
			s = append(s, '\\', 't')
		default:
			s = append(s, c)
		}
	}
	return string(s)
}
